### ISSUE TITLE
Where is the module "lib.visualization_callbacks"

### ISSUE THREAD

**Issue by Tomoki-0526** [MichaelRamamonjisoa/MonteBoxFinder#1]
When running the optimization code, it reported **_ModuleNotFoundError: No module named 'lib.visualization_callbacks'_**, but I didn't find anywhere about this module in the project. How can I solve the problem?

**Comment by MichaelRamamonjisoa** [comment]
Hi, thanks for your interest and sorry for the delay. Hope you found the solution before, pushed a fix in 1940d65fe26339f1e5c10566990b159494f66b7f.
