### ISSUE TITLE
NameError: name 'MCTSOptimizer' is not defined

### ISSUE THREAD

**Issue by Nicwhu** [MichaelRamamonjisoa/MonteBoxFinder#2]
Hi, i am interested in your excellent work. However, i cannot get the final result when run 'python run.py...', and the error is "NameError: name 'MCTSOptimizer' is not defined" in the ./lib/optimizer.py.

**Comment by micramamonjisoa** [comment]
Hi, thanks for your interest! Sorry to reply so late, I had solved the problem in commit e516747730f13fcdb8c061c5e7fa5b37b244876d
