### ISSUE TITLE
A question about the bounding boxes in the visual results.

### ISSUE THREAD

**Issue by Tomoki-0526** [MichaelRamamonjisoa/MonteBoxFinder#3]
Thank you very much for your reply in issue #1 and there is still a question left. I want to know whether the bounding boxes in your rendering are compact or not, cause I find there seems to be no standard. For example in Fig. 5, a chair can be surrounded by only one big box and also can be partly framed by two boxes, one of which is corresponding to the back and another is to the sitting part.

**Comment by MichaelRamamonjisoa** [comment]
Hi, and thanks again for your interest in our work.
The problem you are raising can indeed occur. Larger boxes can explain the back and the seat of a chair, while we would want two "planar" cuboids to explain it.
Similarly, a partially scanned desk could be scanned in only two or three faces, and we would like a cuboid to explain the unobserved parts. 
While this completion ability is desirable in most cases, one drawback is the one you mentioned, making it a limitation of our work.

A potential next step would be to locally (in 3D) optimize this local minimum of the loss function in parts of the scene that need refinement.

**Comment by Tomoki-0526** [comment]
Thanks again for your detailed reply!
